/* eslint-disable */
/* tslint:disable */
// noinspection JSUnusedGlobalSymbols
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero. ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/0xcadams/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { default as zeroSchema } from '@openfaith/zero/drizzle-zero.config'
import type { ZeroCustomType } from 'drizzle-zero'

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  relationships: {
    adapterDetails: {
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
    },
    adapterTokens: {
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
      user: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'users',
          sourceField: ['userId'],
        },
      ],
    },
    addresses: {
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
      sourceEdges: [
        {
          cardinality: 'many',
          destField: ['sourceEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
      targetEdges: [
        {
          cardinality: 'many',
          destField: ['targetEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
    },
    campuses: {
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
      sourceEdges: [
        {
          cardinality: 'many',
          destField: ['sourceEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
      targetEdges: [
        {
          cardinality: 'many',
          destField: ['targetEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
    },
    edges: {
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
      sourceAddress: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'addresses',
          sourceField: ['sourceEntityId'],
        },
      ],
      sourceCampus: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'campuses',
          sourceField: ['sourceEntityId'],
        },
      ],
      sourceFolder: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'folders',
          sourceField: ['sourceEntityId'],
        },
      ],
      sourceOrg: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'orgs',
          sourceField: ['sourceEntityId'],
        },
      ],
      sourcePerson: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'people',
          sourceField: ['sourceEntityId'],
        },
      ],
      sourcePhoneNumber: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'phoneNumbers',
          sourceField: ['sourceEntityId'],
        },
      ],
      sourceUser: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'users',
          sourceField: ['sourceEntityId'],
        },
      ],
      targetAddress: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'addresses',
          sourceField: ['targetEntityId'],
        },
      ],
      targetCampus: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'campuses',
          sourceField: ['targetEntityId'],
        },
      ],
      targetFolder: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'folders',
          sourceField: ['targetEntityId'],
        },
      ],
      targetOrg: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'orgs',
          sourceField: ['targetEntityId'],
        },
      ],
      targetPerson: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'people',
          sourceField: ['targetEntityId'],
        },
      ],
      targetPhoneNumber: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'phoneNumbers',
          sourceField: ['targetEntityId'],
        },
      ],
      targetUser: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'users',
          sourceField: ['targetEntityId'],
        },
      ],
    },
    externalLinks: {
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
    },
    folders: {
      childFolders: [
        {
          cardinality: 'many',
          destField: ['parentFolderId'],
          destSchema: 'folders',
          sourceField: ['id'],
        },
      ],
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
      parentFolder: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'folders',
          sourceField: ['parentFolderId'],
        },
      ],
      sourceEdges: [
        {
          cardinality: 'many',
          destField: ['sourceEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
      targetEdges: [
        {
          cardinality: 'many',
          destField: ['targetEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
    },
    invitations: {
      inviter: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'users',
          sourceField: ['inviterId'],
        },
      ],
      inviterOrgUser: [
        {
          cardinality: 'one',
          destField: ['userId'],
          destSchema: 'orgUsers',
          sourceField: ['inviterId'],
        },
      ],
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
    },
    orgSettings: {
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
      orgUsers: [
        {
          cardinality: 'many',
          destField: ['orgId'],
          destSchema: 'orgUsers',
          sourceField: ['orgId'],
        },
      ],
    },
    orgs: {
      adapterDetails: [
        {
          cardinality: 'many',
          destField: ['orgId'],
          destSchema: 'adapterDetails',
          sourceField: ['id'],
        },
      ],
      adapterTokens: [
        {
          cardinality: 'many',
          destField: ['orgId'],
          destSchema: 'adapterTokens',
          sourceField: ['id'],
        },
      ],
      edges: [
        {
          cardinality: 'many',
          destField: ['orgId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
      externalLinks: [
        {
          cardinality: 'many',
          destField: ['orgId'],
          destSchema: 'externalLinks',
          sourceField: ['id'],
        },
      ],
      invitations: [
        {
          cardinality: 'many',
          destField: ['orgId'],
          destSchema: 'invitations',
          sourceField: ['id'],
        },
      ],
      orgUsers: [
        {
          cardinality: 'many',
          destField: ['orgId'],
          destSchema: 'orgUsers',
          sourceField: ['id'],
        },
      ],
      people: [
        {
          cardinality: 'many',
          destField: ['orgId'],
          destSchema: 'people',
          sourceField: ['id'],
        },
      ],
      phoneNumbers: [
        {
          cardinality: 'many',
          destField: ['orgId'],
          destSchema: 'phoneNumbers',
          sourceField: ['id'],
        },
      ],
      settings: [
        {
          cardinality: 'one',
          destField: ['orgId'],
          destSchema: 'orgSettings',
          sourceField: ['id'],
        },
      ],
      sourceEdges: [
        {
          cardinality: 'many',
          destField: ['sourceEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
      targetEdges: [
        {
          cardinality: 'many',
          destField: ['targetEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
    },
    orgUsers: {
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
      orgSettings: [
        {
          cardinality: 'one',
          destField: ['orgId'],
          destSchema: 'orgSettings',
          sourceField: ['orgId'],
        },
      ],
      sentInvitations: [
        {
          cardinality: 'many',
          destField: ['inviterId'],
          destSchema: 'invitations',
          sourceField: ['userId'],
        },
      ],
      user: [
        {
          cardinality: 'one',
          destField: ['id'],
          destSchema: 'users',
          sourceField: ['userId'],
        },
      ],
    },
    people: {
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
      sourceEdges: [
        {
          cardinality: 'many',
          destField: ['sourceEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
      targetEdges: [
        {
          cardinality: 'many',
          destField: ['targetEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
    },
    phoneNumbers: {
      org: [{ cardinality: 'one', destField: ['id'], destSchema: 'orgs', sourceField: ['orgId'] }],
      sourceEdges: [
        {
          cardinality: 'many',
          destField: ['sourceEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
      targetEdges: [
        {
          cardinality: 'many',
          destField: ['targetEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
    },
    users: {
      adapterTokens: [
        {
          cardinality: 'many',
          destField: ['userId'],
          destSchema: 'adapterTokens',
          sourceField: ['id'],
        },
      ],
      orgUsers: [
        {
          cardinality: 'many',
          destField: ['userId'],
          destSchema: 'orgUsers',
          sourceField: ['id'],
        },
      ],
      sentInvitations: [
        {
          cardinality: 'many',
          destField: ['inviterId'],
          destSchema: 'invitations',
          sourceField: ['id'],
        },
      ],
      sourceEdges: [
        {
          cardinality: 'many',
          destField: ['sourceEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
      targetEdges: [
        {
          cardinality: 'many',
          destField: ['targetEntityId'],
          destSchema: 'edges',
          sourceField: ['id'],
        },
      ],
    },
  },
  tables: {
    adapterDetails: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterDetailsTable',
            '_tag'
          >,
          optional: false,
          type: 'string',
        },
        adapter: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterDetailsTable',
            'adapter'
          >,
          optional: false,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterDetailsTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        enabled: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterDetailsTable',
            'enabled'
          >,
          optional: false,
          type: 'boolean',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterDetailsTable',
            'orgId'
          >,
          optional: false,
          type: 'string',
        },
        syncStatus: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterDetailsTable',
            'syncStatus'
          >,
          optional: false,
          type: 'json',
        },
      },
      name: 'adapterDetails',
      primaryKey: ['orgId', 'adapter'],
      serverName: 'openfaith_adapterDetails',
    },
    adapterTokens: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterTokensTable',
            '_tag'
          >,
          optional: false,
          type: 'string',
        },
        accessToken: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterTokensTable',
            'accessToken'
          >,
          optional: false,
          type: 'string',
        },
        adapter: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterTokensTable',
            'adapter'
          >,
          optional: false,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterTokensTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        expiresIn: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterTokensTable',
            'expiresIn'
          >,
          optional: false,
          type: 'number',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterTokensTable',
            'orgId'
          >,
          optional: false,
          type: 'string',
        },
        refreshToken: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterTokensTable',
            'refreshToken'
          >,
          optional: false,
          type: 'string',
        },
        userId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'adapterTokensTable',
            'userId'
          >,
          optional: false,
          type: 'string',
        },
      },
      name: 'adapterTokens',
      primaryKey: ['userId', 'orgId', 'adapter'],
      serverName: 'openfaith_adapterTokens',
    },
    addresses: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            '_tag'
          >,
          optional: false,
          type: 'string',
        },
        city: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'city'
          >,
          optional: true,
          type: 'string',
        },
        countryCode: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'countryCode'
          >,
          optional: true,
          type: 'string',
        },
        countryName: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'countryName'
          >,
          optional: true,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        createdBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'createdBy'
          >,
          optional: true,
          type: 'string',
        },
        customFields: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'customFields'
          >,
          optional: true,
          type: 'json',
        },
        deletedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'deletedAt'
          >,
          optional: true,
          type: 'number',
        },
        deletedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'deletedBy'
          >,
          optional: true,
          type: 'string',
        },
        externalIds: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'externalIds'
          >,
          optional: true,
          type: 'json',
        },
        id: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'addressesTable', 'id'>,
          optional: false,
          type: 'string',
        },
        inactivatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'inactivatedAt'
          >,
          optional: true,
          type: 'number',
        },
        inactivatedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'inactivatedBy'
          >,
          optional: true,
          type: 'string',
        },
        location: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'location'
          >,
          optional: true,
          type: 'string',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'orgId'
          >,
          optional: false,
          type: 'string',
        },
        primary: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'primary'
          >,
          optional: true,
          type: 'boolean',
        },
        state: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'state'
          >,
          optional: true,
          type: 'string',
        },
        status: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'status'
          >,
          optional: true,
          type: 'string',
        },
        streetLine1: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'streetLine1'
          >,
          optional: true,
          type: 'string',
        },
        streetLine2: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'streetLine2'
          >,
          optional: true,
          type: 'string',
        },
        tags: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'tags'
          >,
          optional: true,
          type: 'json',
        },
        type: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'type'
          >,
          optional: true,
          type: 'string',
        },
        updatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'updatedAt'
          >,
          optional: true,
          type: 'number',
        },
        updatedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'addressesTable',
            'updatedBy'
          >,
          optional: true,
          type: 'string',
        },
        zip: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'addressesTable', 'zip'>,
          optional: true,
          type: 'string',
        },
      },
      name: 'addresses',
      primaryKey: ['id'],
      serverName: 'openfaith_addresses',
    },
    campuses: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'campusesTable', '_tag'>,
          optional: false,
          type: 'string',
        },
        avatar: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'avatar'
          >,
          optional: true,
          type: 'string',
        },
        city: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'campusesTable', 'city'>,
          optional: true,
          type: 'string',
        },
        country: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'country'
          >,
          optional: true,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        createdBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'createdBy'
          >,
          optional: true,
          type: 'string',
        },
        customFields: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'customFields'
          >,
          optional: true,
          type: 'json',
        },
        deletedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'deletedAt'
          >,
          optional: true,
          type: 'number',
        },
        deletedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'deletedBy'
          >,
          optional: true,
          type: 'string',
        },
        description: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'description'
          >,
          optional: true,
          type: 'string',
        },
        externalIds: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'externalIds'
          >,
          optional: true,
          type: 'json',
        },
        id: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'campusesTable', 'id'>,
          optional: false,
          type: 'string',
        },
        inactivatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'inactivatedAt'
          >,
          optional: true,
          type: 'number',
        },
        inactivatedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'inactivatedBy'
          >,
          optional: true,
          type: 'string',
        },
        latitude: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'latitude'
          >,
          optional: true,
          type: 'number',
        },
        longitude: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'longitude'
          >,
          optional: true,
          type: 'number',
        },
        name: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'campusesTable', 'name'>,
          optional: false,
          type: 'string',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'orgId'
          >,
          optional: false,
          type: 'string',
        },
        state: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'state'
          >,
          optional: true,
          type: 'string',
        },
        status: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'status'
          >,
          optional: true,
          type: 'string',
        },
        street: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'street'
          >,
          optional: true,
          type: 'string',
        },
        tags: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'campusesTable', 'tags'>,
          optional: true,
          type: 'json',
        },
        type: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'campusesTable', 'type'>,
          optional: true,
          type: 'string',
        },
        updatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'updatedAt'
          >,
          optional: true,
          type: 'number',
        },
        updatedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'campusesTable',
            'updatedBy'
          >,
          optional: true,
          type: 'string',
        },
        url: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'campusesTable', 'url'>,
          optional: true,
          type: 'string',
        },
        zip: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'campusesTable', 'zip'>,
          optional: true,
          type: 'string',
        },
      },
      name: 'campuses',
      primaryKey: ['id'],
      serverName: 'openfaith_campuses',
    },
    edges: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'edgesTable', '_tag'>,
          optional: false,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        createdBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'createdBy'
          >,
          optional: true,
          type: 'string',
        },
        deletedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'deletedAt'
          >,
          optional: true,
          type: 'number',
        },
        deletedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'deletedBy'
          >,
          optional: true,
          type: 'string',
        },
        metadata: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'metadata'
          >,
          optional: true,
          type: 'json',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'edgesTable', 'orgId'>,
          optional: false,
          type: 'string',
        },
        relationshipType: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'relationshipType'
          >,
          optional: false,
          type: 'string',
        },
        sourceEntityId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'sourceEntityId'
          >,
          optional: false,
          type: 'string',
        },
        sourceEntityTypeTag: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'sourceEntityTypeTag'
          >,
          optional: false,
          type: 'string',
        },
        targetEntityId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'targetEntityId'
          >,
          optional: false,
          type: 'string',
        },
        targetEntityTypeTag: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'targetEntityTypeTag'
          >,
          optional: false,
          type: 'string',
        },
        updatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'updatedAt'
          >,
          optional: true,
          type: 'number',
        },
        updatedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'edgesTable',
            'updatedBy'
          >,
          optional: true,
          type: 'string',
        },
      },
      name: 'edges',
      primaryKey: ['orgId', 'sourceEntityId', 'targetEntityId', 'relationshipType'],
      serverName: 'openfaith_edges',
    },
    externalLinks: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            '_tag'
          >,
          optional: false,
          type: 'string',
        },
        adapter: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            'adapter'
          >,
          optional: false,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        deletedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            'deletedAt'
          >,
          optional: true,
          type: 'number',
        },
        deletedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            'deletedBy'
          >,
          optional: true,
          type: 'string',
        },
        entityId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            'entityId'
          >,
          optional: false,
          type: 'string',
        },
        entityType: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            'entityType'
          >,
          optional: false,
          type: 'string',
        },
        externalId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            'externalId'
          >,
          optional: false,
          type: 'string',
        },
        lastProcessedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            'lastProcessedAt'
          >,
          optional: false,
          type: 'number',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            'orgId'
          >,
          optional: false,
          type: 'string',
        },
        syncing: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            'syncing'
          >,
          optional: true,
          type: 'boolean',
        },
        updatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'externalLinksTable',
            'updatedAt'
          >,
          optional: true,
          type: 'number',
        },
      },
      name: 'externalLinks',
      primaryKey: ['orgId', 'adapter', 'externalId'],
      serverName: 'openfaith_externalLinks',
    },
    folders: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'foldersTable', '_tag'>,
          optional: false,
          type: 'string',
        },
        color: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'foldersTable', 'color'>,
          optional: true,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        createdBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'createdBy'
          >,
          optional: true,
          type: 'string',
        },
        customFields: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'customFields'
          >,
          optional: true,
          type: 'json',
        },
        deletedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'deletedAt'
          >,
          optional: true,
          type: 'number',
        },
        deletedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'deletedBy'
          >,
          optional: true,
          type: 'string',
        },
        description: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'description'
          >,
          optional: true,
          type: 'string',
        },
        externalIds: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'externalIds'
          >,
          optional: true,
          type: 'json',
        },
        folderType: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'folderType'
          >,
          optional: true,
          type: 'string',
        },
        icon: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'foldersTable', 'icon'>,
          optional: true,
          type: 'string',
        },
        id: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'foldersTable', 'id'>,
          optional: false,
          type: 'string',
        },
        name: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'foldersTable', 'name'>,
          optional: false,
          type: 'string',
        },
        orderingKey: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'orderingKey'
          >,
          optional: true,
          type: 'string',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'foldersTable', 'orgId'>,
          optional: false,
          type: 'string',
        },
        parentFolderId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'parentFolderId'
          >,
          optional: true,
          type: 'string',
        },
        tags: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'foldersTable', 'tags'>,
          optional: true,
          type: 'json',
        },
        updatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'updatedAt'
          >,
          optional: true,
          type: 'number',
        },
        updatedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'foldersTable',
            'updatedBy'
          >,
          optional: true,
          type: 'string',
        },
      },
      name: 'folders',
      primaryKey: ['id'],
      serverName: 'openfaith_folders',
    },
    invitations: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'invitationsTable',
            '_tag'
          >,
          optional: false,
          type: 'string',
        },
        email: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'invitationsTable',
            'email'
          >,
          optional: false,
          type: 'string',
        },
        expiresAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'invitationsTable',
            'expiresAt'
          >,
          optional: false,
          type: 'number',
        },
        id: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'invitationsTable',
            'id'
          >,
          optional: false,
          type: 'string',
        },
        inviterId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'invitationsTable',
            'inviterId'
          >,
          optional: false,
          type: 'string',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'invitationsTable',
            'orgId'
          >,
          optional: false,
          type: 'string',
        },
        role: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'invitationsTable',
            'role'
          >,
          optional: true,
          type: 'string',
        },
        status: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'invitationsTable',
            'status'
          >,
          optional: false,
          type: 'string',
        },
      },
      name: 'invitations',
      primaryKey: ['id'],
      serverName: 'openfaith_invitations',
    },
    jwks: {
      columns: {
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'jwksTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        id: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'jwksTable', 'id'>,
          optional: false,
          type: 'string',
        },
        privateKey: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'jwksTable',
            'privateKey'
          >,
          optional: false,
          type: 'string',
        },
        publicKey: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'jwksTable',
            'publicKey'
          >,
          optional: false,
          type: 'string',
        },
      },
      name: 'jwks',
      primaryKey: ['id'],
      serverName: 'openfaith_jwks',
    },
    orgSettings: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'orgSettingsTable',
            '_tag'
          >,
          optional: false,
          type: 'string',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'orgSettingsTable',
            'orgId'
          >,
          optional: false,
          type: 'string',
        },
      },
      name: 'orgSettings',
      primaryKey: ['orgId'],
      serverName: 'openfaith_orgSettings',
    },
    orgs: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'orgsTable', '_tag'>,
          optional: false,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'orgsTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        id: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'orgsTable', 'id'>,
          optional: false,
          type: 'string',
        },
        logo: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'orgsTable', 'logo'>,
          optional: true,
          type: 'string',
        },
        metadata: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'orgsTable', 'metadata'>,
          optional: true,
          type: 'string',
        },
        name: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'orgsTable', 'name'>,
          optional: false,
          type: 'string',
        },
        slug: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'orgsTable', 'slug'>,
          optional: true,
          type: 'string',
        },
      },
      name: 'orgs',
      primaryKey: ['id'],
      serverName: 'openfaith_orgs',
    },
    orgUsers: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'orgUsersTable', '_tag'>,
          optional: false,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'orgUsersTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        id: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'orgUsersTable', 'id'>,
          optional: false,
          type: 'string',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'orgUsersTable',
            'orgId'
          >,
          optional: false,
          type: 'string',
        },
        role: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'orgUsersTable', 'role'>,
          optional: false,
          type: 'string',
        },
        userId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'orgUsersTable',
            'userId'
          >,
          optional: false,
          type: 'string',
        },
      },
      name: 'orgUsers',
      primaryKey: ['id'],
      serverName: 'openfaith_orgUsers',
    },
    people: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'peopleTable', '_tag'>,
          optional: false,
          type: 'string',
        },
        anniversary: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'anniversary'
          >,
          optional: true,
          type: 'string',
        },
        avatar: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'peopleTable', 'avatar'>,
          optional: true,
          type: 'string',
        },
        birthdate: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'birthdate'
          >,
          optional: true,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        createdBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'createdBy'
          >,
          optional: true,
          type: 'string',
        },
        customFields: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'customFields'
          >,
          optional: true,
          type: 'json',
        },
        deletedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'deletedAt'
          >,
          optional: true,
          type: 'number',
        },
        deletedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'deletedBy'
          >,
          optional: true,
          type: 'string',
        },
        externalIds: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'externalIds'
          >,
          optional: true,
          type: 'json',
        },
        firstName: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'firstName'
          >,
          optional: true,
          type: 'string',
        },
        gender: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'peopleTable', 'gender'>,
          optional: true,
          type: 'string',
        },
        id: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'peopleTable', 'id'>,
          optional: false,
          type: 'string',
        },
        inactivatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'inactivatedAt'
          >,
          optional: true,
          type: 'number',
        },
        inactivatedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'inactivatedBy'
          >,
          optional: true,
          type: 'string',
        },
        lastName: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'lastName'
          >,
          optional: true,
          type: 'string',
        },
        membership: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'membership'
          >,
          optional: true,
          type: 'string',
        },
        middleName: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'middleName'
          >,
          optional: true,
          type: 'string',
        },
        name: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'peopleTable', 'name'>,
          optional: true,
          type: 'string',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'peopleTable', 'orgId'>,
          optional: false,
          type: 'string',
        },
        status: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'peopleTable', 'status'>,
          optional: true,
          type: 'string',
        },
        tags: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'peopleTable', 'tags'>,
          optional: true,
          type: 'json',
        },
        type: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'peopleTable', 'type'>,
          optional: true,
          type: 'string',
        },
        updatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'updatedAt'
          >,
          optional: true,
          type: 'number',
        },
        updatedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'peopleTable',
            'updatedBy'
          >,
          optional: true,
          type: 'string',
        },
      },
      name: 'people',
      primaryKey: ['id'],
      serverName: 'openfaith_people',
    },
    phoneNumbers: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            '_tag'
          >,
          optional: false,
          type: 'string',
        },
        countryCode: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'countryCode'
          >,
          optional: true,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        createdBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'createdBy'
          >,
          optional: true,
          type: 'string',
        },
        customFields: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'customFields'
          >,
          optional: true,
          type: 'json',
        },
        deletedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'deletedAt'
          >,
          optional: true,
          type: 'number',
        },
        deletedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'deletedBy'
          >,
          optional: true,
          type: 'string',
        },
        externalIds: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'externalIds'
          >,
          optional: true,
          type: 'json',
        },
        id: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'id'
          >,
          optional: false,
          type: 'string',
        },
        inactivatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'inactivatedAt'
          >,
          optional: true,
          type: 'number',
        },
        inactivatedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'inactivatedBy'
          >,
          optional: true,
          type: 'string',
        },
        location: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'location'
          >,
          optional: true,
          type: 'string',
        },
        number: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'number'
          >,
          optional: true,
          type: 'string',
        },
        orgId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'orgId'
          >,
          optional: false,
          type: 'string',
        },
        primary: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'primary'
          >,
          optional: true,
          type: 'boolean',
        },
        status: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'status'
          >,
          optional: true,
          type: 'string',
        },
        tags: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'tags'
          >,
          optional: true,
          type: 'json',
        },
        type: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'type'
          >,
          optional: true,
          type: 'string',
        },
        updatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'updatedAt'
          >,
          optional: true,
          type: 'number',
        },
        updatedBy: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'phoneNumbersTable',
            'updatedBy'
          >,
          optional: true,
          type: 'string',
        },
      },
      name: 'phoneNumbers',
      primaryKey: ['id'],
      serverName: 'openfaith_phoneNumbers',
    },
    users: {
      columns: {
        _tag: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'usersTable', '_tag'>,
          optional: false,
          type: 'string',
        },
        banExpires: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'usersTable',
            'banExpires'
          >,
          optional: true,
          type: 'number',
        },
        banned: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'usersTable', 'banned'>,
          optional: true,
          type: 'boolean',
        },
        banReason: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'usersTable',
            'banReason'
          >,
          optional: true,
          type: 'string',
        },
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'usersTable',
            'createdAt'
          >,
          optional: false,
          type: 'number',
        },
        email: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'usersTable', 'email'>,
          optional: false,
          type: 'string',
        },
        emailVerified: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'usersTable',
            'emailVerified'
          >,
          optional: false,
          type: 'boolean',
        },
        id: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'usersTable', 'id'>,
          optional: false,
          type: 'string',
        },
        image: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'usersTable', 'image'>,
          optional: true,
          type: 'string',
        },
        isAnonymous: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'usersTable',
            'isAnonymous'
          >,
          optional: true,
          type: 'boolean',
        },
        name: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'usersTable', 'name'>,
          optional: false,
          type: 'string',
        },
        role: {
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'usersTable', 'role'>,
          optional: true,
          type: 'string',
        },
        stripeCustomerId: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'usersTable',
            'stripeCustomerId'
          >,
          optional: true,
          type: 'string',
        },
        updatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'usersTable',
            'updatedAt'
          >,
          optional: false,
          type: 'number',
        },
      },
      name: 'users',
      primaryKey: ['id'],
      serverName: 'openfaith_users',
    },
    verifications: {
      columns: {
        createdAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'verificationsTable',
            'createdAt'
          >,
          optional: true,
          type: 'number',
        },
        expiresAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'verificationsTable',
            'expiresAt'
          >,
          optional: false,
          type: 'number',
        },
        id: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'verificationsTable',
            'id'
          >,
          optional: false,
          type: 'string',
        },
        identifier: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'verificationsTable',
            'identifier'
          >,
          optional: false,
          type: 'string',
        },
        updatedAt: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'verificationsTable',
            'updatedAt'
          >,
          optional: true,
          type: 'number',
        },
        value: {
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'verificationsTable',
            'value'
          >,
          optional: false,
          type: 'string',
        },
      },
      name: 'verifications',
      primaryKey: ['id'],
      serverName: 'openfaith_verifications',
    },
  },
} as const

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema
