apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zero-replica-pvc
  namespace: openfaith
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
