/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as OauthProviderImport } from './routes/oauth/$provider'
import { Route as authAuthLayoutImport } from './routes/(auth)/_authLayout'
import { Route as appAppLayoutImport } from './routes/(app)/_appLayout'
import { Route as authAuthLayoutSignInImport } from './routes/(auth)/_authLayout.sign-in'
import { Route as appAppLayoutDashboardImport } from './routes/(app)/_appLayout.dashboard'

// Create Virtual Routes

const authImport = createFileRoute('/(auth)')()
const appImport = createFileRoute('/(app)')()

// Create/Update Routes

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const appRoute = appImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OauthProviderRoute = OauthProviderImport.update({
  id: '/oauth/$provider',
  path: '/oauth/$provider',
  getParentRoute: () => rootRoute,
} as any)

const authAuthLayoutRoute = authAuthLayoutImport.update({
  id: '/_authLayout',
  getParentRoute: () => authRoute,
} as any)

const appAppLayoutRoute = appAppLayoutImport.update({
  id: '/_appLayout',
  getParentRoute: () => appRoute,
} as any)

const authAuthLayoutSignInRoute = authAuthLayoutSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authAuthLayoutRoute,
} as any)

const appAppLayoutDashboardRoute = appAppLayoutDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appAppLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appImport
      parentRoute: typeof rootRoute
    }
    '/(app)/_appLayout': {
      id: '/(app)/_appLayout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appAppLayoutImport
      parentRoute: typeof appRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_authLayout': {
      id: '/(auth)/_authLayout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthLayoutImport
      parentRoute: typeof authRoute
    }
    '/oauth/$provider': {
      id: '/oauth/$provider'
      path: '/oauth/$provider'
      fullPath: '/oauth/$provider'
      preLoaderRoute: typeof OauthProviderImport
      parentRoute: typeof rootRoute
    }
    '/(app)/_appLayout/dashboard': {
      id: '/(app)/_appLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appAppLayoutDashboardImport
      parentRoute: typeof appAppLayoutImport
    }
    '/(auth)/_authLayout/sign-in': {
      id: '/(auth)/_authLayout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authAuthLayoutSignInImport
      parentRoute: typeof authAuthLayoutImport
    }
  }
}

// Create and export the route tree

interface appAppLayoutRouteChildren {
  appAppLayoutDashboardRoute: typeof appAppLayoutDashboardRoute
}

const appAppLayoutRouteChildren: appAppLayoutRouteChildren = {
  appAppLayoutDashboardRoute: appAppLayoutDashboardRoute,
}

const appAppLayoutRouteWithChildren = appAppLayoutRoute._addFileChildren(
  appAppLayoutRouteChildren,
)

interface appRouteChildren {
  appAppLayoutRoute: typeof appAppLayoutRouteWithChildren
}

const appRouteChildren: appRouteChildren = {
  appAppLayoutRoute: appAppLayoutRouteWithChildren,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

interface authAuthLayoutRouteChildren {
  authAuthLayoutSignInRoute: typeof authAuthLayoutSignInRoute
}

const authAuthLayoutRouteChildren: authAuthLayoutRouteChildren = {
  authAuthLayoutSignInRoute: authAuthLayoutSignInRoute,
}

const authAuthLayoutRouteWithChildren = authAuthLayoutRoute._addFileChildren(
  authAuthLayoutRouteChildren,
)

interface authRouteChildren {
  authAuthLayoutRoute: typeof authAuthLayoutRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authAuthLayoutRoute: authAuthLayoutRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof authAuthLayoutRouteWithChildren
  '/oauth/$provider': typeof OauthProviderRoute
  '/dashboard': typeof appAppLayoutDashboardRoute
  '/sign-in': typeof authAuthLayoutSignInRoute
}

export interface FileRoutesByTo {
  '/': typeof authAuthLayoutRouteWithChildren
  '/oauth/$provider': typeof OauthProviderRoute
  '/dashboard': typeof appAppLayoutDashboardRoute
  '/sign-in': typeof authAuthLayoutSignInRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(app)': typeof appRouteWithChildren
  '/(app)/_appLayout': typeof appAppLayoutRouteWithChildren
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_authLayout': typeof authAuthLayoutRouteWithChildren
  '/oauth/$provider': typeof OauthProviderRoute
  '/(app)/_appLayout/dashboard': typeof appAppLayoutDashboardRoute
  '/(auth)/_authLayout/sign-in': typeof authAuthLayoutSignInRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oauth/$provider' | '/dashboard' | '/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oauth/$provider' | '/dashboard' | '/sign-in'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/_appLayout'
    | '/(auth)'
    | '/(auth)/_authLayout'
    | '/oauth/$provider'
    | '/(app)/_appLayout/dashboard'
    | '/(auth)/_authLayout/sign-in'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRoute: typeof appRouteWithChildren
  authRoute: typeof authRouteWithChildren
  OauthProviderRoute: typeof OauthProviderRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRoute: appRouteWithChildren,
  authRoute: authRouteWithChildren,
  OauthProviderRoute: OauthProviderRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(app)",
        "/(auth)",
        "/oauth/$provider"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(app)": {
      "filePath": "(app)",
      "children": [
        "/(app)/_appLayout"
      ]
    },
    "/(app)/_appLayout": {
      "filePath": "(app)/_appLayout.tsx",
      "parent": "/(app)",
      "children": [
        "/(app)/_appLayout/dashboard"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_authLayout"
      ]
    },
    "/(auth)/_authLayout": {
      "filePath": "(auth)/_authLayout.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_authLayout/sign-in"
      ]
    },
    "/oauth/$provider": {
      "filePath": "oauth/$provider.tsx"
    },
    "/(app)/_appLayout/dashboard": {
      "filePath": "(app)/_appLayout.dashboard.tsx",
      "parent": "/(app)/_appLayout"
    },
    "/(auth)/_authLayout/sign-in": {
      "filePath": "(auth)/_authLayout.sign-in.tsx",
      "parent": "/(auth)/_authLayout"
    }
  }
}
ROUTE_MANIFEST_END */
