ALTER TABLE "openfaith_adapterDetails" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_adapterTokens" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_addresses" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_addresses" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_addresses" ALTER COLUMN "inactivatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_addresses" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_campuses" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_campuses" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_campuses" ALTER COLUMN "inactivatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_campuses" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_edges" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_edges" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_edges" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_entityRelationships" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_entityRelationships" ALTER COLUMN "updatedAt" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "openfaith_externalLinks" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_externalLinks" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_externalLinks" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_fieldOptions" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_fieldOptions" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_fieldOptions" ALTER COLUMN "inactivatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_fieldOptions" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_fields" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_fields" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_fields" ALTER COLUMN "inactivatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_fields" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_folders" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_folders" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_folders" ALTER COLUMN "inactivatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_folders" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_invitations" ALTER COLUMN "expiresAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_journeys" ALTER COLUMN "completedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_journeys" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_journeys" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_journeys" ALTER COLUMN "inactivatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_journeys" ALTER COLUMN "lastActivityAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_journeys" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_jwks" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_orgs" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_orgUsers" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_pathways" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_pathways" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_pathways" ALTER COLUMN "inactivatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_pathways" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_people" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_people" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_people" ALTER COLUMN "inactivatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_people" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_phoneNumbers" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_phoneNumbers" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_phoneNumbers" ALTER COLUMN "inactivatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_phoneNumbers" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_qualifications" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_qualifications" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_qualifications" ALTER COLUMN "inactivatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_qualifications" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_sacraments" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_sacraments" ALTER COLUMN "deletedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_sacraments" ALTER COLUMN "inactivatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_sacraments" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_users" ALTER COLUMN "banExpires" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_users" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_users" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_verifications" ALTER COLUMN "createdAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_verifications" ALTER COLUMN "expiresAt" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "openfaith_verifications" ALTER COLUMN "updatedAt" SET DATA TYPE timestamp with time zone;