name: Build and Push Docker Images

on:
  push:
    branches: [ k8s-support ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service:
          - name: frontend
            context: .
            dockerfile: apps/openfaith/Dockerfile
          - name: backend
            context: .
            dockerfile: backend/server/Dockerfile
          - name: workers
            context: .
            dockerfile: backend/workers/Dockerfile
          - name: shard-manager
            context: .
            dockerfile: backend/shard-manager/Dockerfile

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.service.name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.service.context }}
        file: ${{ matrix.service.dockerfile }}
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          ${{ matrix.service.name == 'frontend' && format('VITE_ZERO_SERVER={0}', vars.VITE_ZERO_SERVER) || '' }}
          ${{ matrix.service.name == 'frontend' && format('VITE_APP_NAME={0}', vars.VITE_APP_NAME) || '' }}
          ${{ matrix.service.name == 'frontend' && format('VITE_BASE_URL={0}', vars.VITE_BASE_URL) || '' }}
          ${{ matrix.service.name == 'frontend' && format('VITE_PROD_ROOT_DOMAIN={0}', vars.VITE_PROD_ROOT_DOMAIN) || '' }}
          ${{ matrix.service.name == 'frontend' && format('VITE_PROD_EMAIL_DOMAIN={0}', vars.VITE_PROD_EMAIL_DOMAIN) || '' }}
          ${{ matrix.service.name == 'frontend' && format('VITE_PLANNING_CENTER_CLIENT_ID={0}', vars.VITE_PLANNING_CENTER_CLIENT_ID) || '' }}
